# Template para configurar secrets no Streamlit Cloud
# Copie este conteúdo e cole na seção "Secrets" do seu app no Streamlit Cloud

GEMINI_API_KEY = "AIzaSyAz9e_t9EEmrjSf24jMHNRsbLchLMGvBVk"
MODEL = "gemini/gemini-1.5-flash"
LLM_TEMPERATURE = "0.7"
LLM_MAX_TOKENS = "2048"
APP_TITLE = "Terapia Familiar MVP"
APP_DESCRIPTION = "Sistema de apoio emocional baseado em Carter & McGoldrick"
DEBUG = "false"
VERBOSE = "true"
